-- INSERT Statements für kinoSystemDB

-- Movie Tabelle (50 Einträge mit 450 Zeichen Beschreibung)
INSERT INTO Movie (image, awards, title, rating, releaseDate, length, ageRating, genre, description) VALUES
                                                                                                         ('inception', 'Oscar Winner', 'Inception', 9, '2010-07-16', 148, 12, 'Science Fiction', 'Dom Cobb ist ein begabter Dieb und in der gefährlichen Kunst der Extraction spezialisiert: Er stiehlt wertvolle Geheimnisse aus dem Unterbewusstsein während des Traums. Diese seltene Fähigkeit macht ihn zu einem begehrten Spieler in der Welt der Wirtschaftsspionage, kostet ihn jedoch alles, was er liebt. Cobb erhält die Chance auf Erlösung: Ein letzter Job könnte ihm sein Leben zurückgeben, aber nur wenn er das Unmögliche schafft - Inception. Statt einen Traum zu stehlen, muss er eine Idee einpflanzen.'),

                                                                                                         ('dark_knight', '2 Oscars', 'The Dark Knight', 9, '2008-07-18', 152, 12, 'Action', 'Batman muss eine der größten psychologischen und physischen Prüfungen seiner Karriere bestehen, um gegen einen kriminellen Mastermind namens Joker anzukämpfen. Mit Hilfe von Lieutenant Jim Gordon und Bezirksstaatsanwalt Harvey Dent versucht Batman, das organisierte Verbrechen in Gotham City zu zerschlagen. Die Allianz erweist sich als erfolgreich, aber sie werden bald selbst zur Beute eines aufkommenden Chaos, das durch das kriminelle Genie des Jokers entfesselt wird und Gotham in Anarchie stürzt.'),

                                                                                                         ('parasite', '4 Oscars', 'Parasite', 9, '2019-05-30', 132, 16, 'Thriller', 'Die arbeitslose Familie Kim lebt in einem schäbigen Souterrain und schlägt sich mit prekären Gelegenheitsjobs durch. Als der Sohn Nachhilfe beim reichen Park-Clan anbietet, öffnet sich eine Tür zur Oberschicht. Nach und nach erschleichen sich alle Familienmitglieder Jobs im luxuriösen Anwesen. Der Kontrast zwischen Arm und Reich könnte nicht größer sein. Doch die neue Existenz ist instabil und ein unerwartetes Ereignis bringt alles ins Wanken. Eine bitterböse Gesellschaftssatire über Klassenunterschiede und den Überlebenskampf.'),

                                                                                                         ('shawshank', '7 Nominations', 'The Shawshank Redemption', 9, '1994-09-23', 142, 12, 'Drama', 'Der Banker Andy Dufresne wird zu lebenslanger Haft im berüchtigten Shawshank-Gefängnis verurteilt, obwohl er seine Unschuld am Mord seiner Frau beteuert. Im Gefängnis freundet er sich mit Red an, einem langjährigen Insassen, der seine Mitgefangenen mit Schmuggelware versorgt. Andy behält trotz der unmenschlichen Bedingungen und korrupten Wärtern seine Würde und Hoffnung. Mit seiner Intelligenz und Geduld verändert er nicht nur das Leben seiner Mitgefangenen, sondern plant auch etwas Außergewöhnliches für seine eigene Zukunft.'),

                                                                                                         ('pulp_fiction', 'Oscar Winner', 'Pulp Fiction', 8, '1994-10-14', 154, 16, 'Crime', 'Die verschlungenen Geschichten von Gangstern, Boxern, kleinen Gaunern und einem mysteriösen Koffer kreuzen sich in Los Angeles. Vincent Vega und Jules Winnfield sind zwei Killer, die für Gangsterboss Marsellus Wallace arbeiten. Vincent muss auf die Frau seines Chefs aufpassen, während Boxer Butch Coolidge einen Deal bricht und flieht. Alle Handlungsstränge sind miteinander verwoben und erzählen von Gewalt, Erlösung, Loyalität und Zufall. Tarantinos Meisterwerk definierte das Kino der 90er Jahre neu mit seinem einzigartigen Stil.'),

                                                                                                         ('godfather', '3 Oscars', 'The Godfather', 9, '1972-03-24', 175, 16, 'Crime', 'Die Geschichte der italienisch-amerikanischen Mafia-Familie Corleone unter der Führung von Patriarch Vito Corleone. Zunächst weigert sich sein jüngster Sohn Michael, in die Familiengeschäfte einzusteigen, doch nach einem Attentat auf seinen Vater wird er tief in die Welt des organisierten Verbrechens hineingezogen. Der Film zeigt den Aufstieg Michaels zum mächtigen Mafia-Boss und die inneren Konflikte zwischen Familie, Loyalität und Macht. Ein episches Meisterwerk über amerikanische Träume, Korruption und die dunkle Seite des Erfolgs.'),

                                                                                                         ('matrix', '4 Oscars', 'The Matrix', 9, '1999-03-31', 136, 16, 'Science Fiction', 'Computer-Hacker Neo erfährt von rebellischen Kämpfern um Morpheus eine schockierende Wahrheit: Die Realität, die er kennt, ist eine Simulation namens Matrix, erschaffen von empfindungsfähigen Maschinen, um die Menschheit zu versklaven. Neos Körper liegt in Wahrheit in einem Tank und dient als Energiequelle. Morpheus glaubt, Neo sei der Auserwählte, der die Menschheit befreien kann. Neo muss lernen, seine wahren Fähigkeiten zu entfesseln und gegen die Agenten kämpfen, die die Matrix beschützen. Eine revolutionäre Science-Fiction-Saga beginnt.'),

                                                                                                         ('forrest_gump', '6 Oscars', 'Forrest Gump', 9, '1994-07-06', 142, 6, 'Drama', 'Forrest Gump sitzt auf einer Parkbank und erzählt Fremden seine außergewöhnliche Lebensgeschichte. Trotz eines niedrigen IQs wird er Football-Star, Vietnam-Kriegsheld, Tischtennismeister, erfolgreicher Unternehmer und inspiriert Elvis Presley. Durch alle historischen Ereignisse der 60er und 70er Jahre bleibt eine Konstante: Seine Liebe zu seiner Jugendfreundin Jenny. Mit kindlicher Naivität und reinem Herzen navigiert Forrest durch das Leben und zeigt, dass Erfolg nicht von Intelligenz abhängt. Eine berührende Geschichte über Liebe, Schicksal und amerikanische Geschichte.'),

                                                                                                         ('fight_club', 'Nominated', 'Fight Club', 8, '1999-10-15', 139, 18, 'Drama', 'Ein namenloser Büroangestellter leidet unter chronischer Schlaflosigkeit und sucht verzweifelt nach einem Sinn in seinem konsumorientierten Leben. Bei einem Selbsthilfegruppen-Besuch trifft er auf den charismatischen Seifenhersteller Tyler Durden. Gemeinsam gründen sie einen geheimen Fight Club, wo Männer ihre Aggressionen ausleben können. Was als therapeutische Prügelei beginnt, entwickelt sich zu einer anarchistischen Bewegung gegen die moderne Gesellschaft. Doch Tyler hat weiterreichende und gefährlichere Pläne. Ein verstörender Trip in die männliche Psyche und Gesellschaftskritik.'),

                                                                                                         ('interstellar', 'Oscar Winner', 'Interstellar', 9, '2014-11-07', 169, 12, 'Science Fiction', 'In naher Zukunft wird die Erde durch Dürren und Sandstürme unbewohnbar. Der ehemalige NASA-Pilot Cooper wird rekrutiert, um eine riskante Mission durch ein Wurmloch zu führen und einen neuen bewohnbaren Planeten für die Menschheit zu finden. Die Reise durch Raum und Zeit testet die Grenzen menschlichen Wissens und Ausdauer. Während Cooper und sein Team ferne Galaxien erforschen, vergeht auf der Erde viel mehr Zeit als im Weltall. Der verzweifelte Kampf um das Überleben der Menschheit wird zu einer emotionalen Reise über Liebe, Opfer und Zeit.'),

                                                                                                         ('gladiator', '5 Oscars', 'Gladiator', 8, '2000-05-05', 155, 16, 'Action', 'General Maximus ist der größte Feldherr des Römischen Reiches und genießt das Vertrauen von Kaiser Marcus Aurelius. Als der Kaiser stirbt und sein korrupter Sohn Commodus die Macht an sich reißt, wird Maximus zum Tode verurteilt. Er entkommt knapp, doch seine Familie wird ermordet. Als Sklave verkauft, wird er zum Gladiator ausgebildet und kämpft sich durch die Arena. Sein Ziel: Rache an Commodus und die Wiederherstellung der römischen Republik. Ein episches Abenteuer über Ehre, Rache und Erlösung im antiken Rom.'),

                                                                                                         ('avengers', 'Nominated', 'Avengers: Endgame', 8, '2019-04-26', 181, 12, 'Action', 'Nach der verheerenden Niederlage gegen Thanos, bei der die Hälfte allen Lebens im Universum ausgelöscht wurde, sind die verbliebenen Avengers am Boden zerstört. Fünf Jahre später ergibt sich eine unerwartete Chance, das Geschehene rückgängig zu machen. Die Helden schmieden einen verzweifelten Plan, der sie durch Zeit und Raum führt, um die Infinity-Steine zu sammeln. Es ist ihre letzte Hoffnung, die Verlorenen zurückzubringen. Doch der Preis für die Rettung des Universums könnte höher sein als sie sich vorstellen können. Das epische Finale der Infinity-Saga.'),

                                                                                                         ('titanic', '11 Oscars', 'Titanic', 8, '1997-12-19', 194, 12, 'Romance', 'An Bord der RMS Titanic, die 1912 zu ihrer Jungfernfahrt aufbricht, treffen der mittellose Künstler Jack und die wohlhabende Rose aufeinander. Trotz ihrer unterschiedlichen sozialen Herkunft verlieben sie sich leidenschaftlich ineinander. Rose soll einen reichen aber arroganten Verlobten heiraten und sieht in Jack eine Fluchtmöglichkeit aus ihrem goldenen Käfig. Ihre Liebesgeschichte erreicht ihren tragischen Höhepunkt, als das als unsinkbar geltende Schiff auf einen Eisberg trifft. Ein monumentales Epos über Liebe, Klassenunterschiede und die historische Katastrophe.'),

                                                                                                         ('jurassic_park', '3 Oscars', 'Jurassic Park', 8, '1993-06-11', 127, 12, 'Adventure', 'Der Milliardär John Hammond hat etwas Unglaubliches geschaffen: Auf einer Insel vor Costa Rica hat er einen Themenpark mit echten Dinosauriern errichtet, geklont aus prähistorischer DNA. Er lädt Experten ein, darunter die Paläontologen Dr. Grant und Dr. Sattler, um den Park zu begutachten. Doch Sabotage legt die Sicherheitssysteme lahm und die Dinosaurier brechen aus. Der Traum wird zum Albtraum, als die prähistorischen Raubtiere Jagd auf die Menschen machen. Ein revolutionärer Blockbuster, der die Grenzen visueller Effekte neu definierte und zum Klassiker wurde.'),

                                                                                                         ('lord_rings', '11 Oscars', 'The Lord of the Rings: Return of the King', 9, '2003-12-17', 201, 12, 'Fantasy', 'Im finalen Kapitel der epischen Trilogie nähert sich Frodo dem Schicksalsberg, um den Einen Ring zu zerstören. Doch die Last des Rings wird immer schwerer und Gollum manipuliert ihn. Währenddessen vereinen Aragorn, Gandalf und ihre Verbündeten alle Kräfte Mittelerdes für die entscheidende Schlacht gegen Saurons Armee vor den Toren Mordors. Das Schicksal der Welt hängt am seidenen Faden. In einer verzweifelten Ablenkung kämpfen sie, um Frodo die Zeit zu verschaffen, die er braucht. Das monumentale Finale einer der größten Filmtrilogien aller Zeiten.'),

                                                                                                         ('star_wars', '6 Oscars', 'Star Wars: Episode V', 9, '1980-05-21', 124, 6, 'Science Fiction', 'Drei Jahre nach der Zerstörung des Todessterns wird die Rebellenbasis auf dem Eisplaneten Hoth von imperialen Truppen angegriffen. Luke Skywalker reist nach Dagobah, um bei Meister Yoda die Jedi-Künste zu erlernen. Währenddessen werden Han Solo und Prinzessin Leia von Darth Vader gejagt. Luke erhält eine schockierende Vision und muss sich entscheiden: Sein Training fortsetzen oder seinen Freunden helfen. Die Konfrontation mit Vader offenbart eine erschütternde Wahrheit über Lukes Vergangenheit. Das dunkelste und beste Kapitel der originalen Star Wars-Trilogie.'),

                                                                                                         ('silence_lambs', '5 Oscars', 'The Silence of the Lambs', 8, '1991-02-14', 118, 16, 'Thriller', 'FBI-Anwärterin Clarice Starling wird beauftragt, den inhaftierten Psychiater und Kannibalen Dr. Hannibal Lecter zu befragen. Das FBI hofft, durch Lecters Einblicke einen Serienmörder namens Buffalo Bill zu fassen, der Frauen entführt und häutet. Zwischen Clarice und Lecter entwickelt sich ein verstörendes psychologisches Duell. Lecter gibt nur dann Hinweise, wenn Clarice persönliche Details aus ihrem Leben preisgibt. Ein Wettlauf gegen die Zeit beginnt, um das nächste Opfer zu retten. Ein intensiver Psycho-Thriller, der unter die Haut geht.'),

                                                                                                         ('schindler', '7 Oscars', 'Schindlers List', 9, '1993-12-15', 195, 12, 'Drama', 'Der opportunistische Geschäftsmann Oskar Schindler kommt nach Krakau, um vom Zweiten Weltkrieg zu profitieren. Er eröffnet eine Fabrik und beschäftigt jüdische Arbeiter, weil sie billiger sind. Doch als er Zeuge der brutalen Judenverfolgung durch die Nazis wird, wandelt sich etwas in ihm. Mit Hilfe seines jüdischen Buchhalters Itzhak Stern beginnt Schindler, über tausend Juden vor der Deportation in Vernichtungslager zu retten, indem er sie als kriegswichtige Arbeiter deklariert. Ein bewegendes Zeitzeugnis über Mut, Menschlichkeit und den Holocaust.'),

                                                                                                         ('green_mile', 'Nominated', 'The Green Mile', 9, '1999-12-10', 189, 12, 'Drama', 'Im Todestrakt eines Gefängnisses in Louisiana während der Großen Depression arbeitet Wärter Paul Edgecomb. Eines Tages wird der sanftmütige Riese John Coffey eingeliefert, verurteilt wegen der Ermordung zweier kleiner Mädchen. Paul entdeckt bald, dass John übernatürliche Heilkräfte besitzt und Schmerzen anderer spüren kann. Zweifel an seiner Schuld kommen auf. Paul muss sich mit moralischen Fragen auseinandersetzen: Was ist Gerechtigkeit? Kann das System einen Unschuldigen hinrichten? Eine tiefgründige Geschichte über Mitgefühl, Ungerechtigkeit und Wunder.'),

                                                                                                         ('prestige', 'Nominated', 'The Prestige', 8, '2006-10-20', 130, 12, 'Mystery', 'London Ende des 19. Jahrhunderts: Die Magier Robert Angier und Alfred Borden sind zunächst Freunde und Partner. Nach einem tragischen Unfall werden sie zu erbitterten Rivalen. Jeder versucht, den anderen mit immer gefährlicheren Illusionen zu übertrumpfen. Als Borden einen scheinbar unmöglichen Trick namens "Die transportierte Person" präsentiert, wird Angier von Besessenheit getrieben, das Geheimnis zu lüften. Seine Obsession führt ihn zu dem exzentrischen Wissenschaftler Nikola Tesla. Ein faszinierender Thriller über Täuschung, Opfer und den Preis der Obsession.'),

                                                                                                         ('departed', '4 Oscars', 'The Departed', 8, '2006-10-06', 151, 16, 'Crime', 'Im korrupten Boston der 90er Jahre schleust Gangsterboss Frank Costello einen Maulwurf in die Polizei ein, während die Polizei einen Undercover-Cop in Costellos Organisation einschleust. Billy Costigan muss seine wahre Identität verbergen und das Vertrauen der Kriminellen gewinnen. Colin Sullivan steigt als Costellos Spion in der Polizei auf. Als beide Seiten erkennen, dass es einen Verräter in ihren Reihen gibt, beginnt ein tödliches Katz-und-Maus-Spiel. Jeder versucht verzweifelt, die Identität des anderen aufzudecken, bevor die eigene auffliegt. Scorseses Meisterwerk des Crime-Thrillers.'),

                                                                                                         ('whiplash', 'Oscar Winner', 'Whiplash', 8, '2014-10-10', 106, 12, 'Drama', 'Der junge Drummer Andrew Neiman träumt davon, einer der größten Jazz-Schlagzeuger zu werden. Er wird in das Studio-Orchester des berüchtigten Dirigenten Terence Fletcher aufgenommen. Doch Fletcher ist ein sadistischer Perfektionist, der seine Schüler mit verbalen und physischen Attacken bis an ihre Grenzen treibt. Andrew ist besessen davon, Fletchers Anerkennung zu erlangen und übt bis zur Selbstzerstörung. Die Beziehung zwischen Lehrer und Schüler eskaliert in einem verstörenden Machtkampf. Eine intensive Studie über Perfektion, Ambition und die Frage, wie weit man für seinen Traum gehen darf.'),

                                                                                                         ('social_network', 'Oscars', 'The Social Network', 8, '2010-10-01', 120, 12, 'Drama', 'Harvard-Student Mark Zuckerberg ist ein sozial unbeholfener Computergenie. Nach einer Trennung hackt er aus Rache die College-Datenbanken und erstellt eine Website zum Vergleichen von Studentinnen. Der Erfolg inspiriert ihn zur Gründung von Facebook. Was als Projekt im Studentenwohnheim beginnt, wird zum globalen Phänomen. Doch auf dem Weg dorthin verrät Mark Freunde und Geschäftspartner. Die Zwillinge Winklevoss und Mitgründer Eduardo Saverin verklagen ihn wegen Ideendiebstahls und Betrugs. Eine packende Geschichte über Ambition, Verrat und die Geburt des Social Media-Zeitalters.'),

                                                                                                         ('grand_budapest', 'Oscar Winner', 'The Grand Budapest Hotel', 8, '2014-03-28', 100, 12, 'Comedy', 'In den 1930er Jahren ist Monsieur Gustave H. der legendäre Concierge des Grand Budapest Hotels in der fiktiven Republik Zubrowka. Er kümmert sich hingebungsvoll um die reichen, älteren Gäste. Als eine seiner Geliebten stirbt und ihm ein wertvolles Gemälde vermacht, wird er des Mordes beschuldigt. Zusammen mit seinem treuen Lobby-Boy Zero begibt er sich auf eine abenteuerliche Flucht durch ein Europa am Rande des Krieges. Wes Andersons visuell umwerfende Komödie ist eine nostalgische Hommage an vergangene Zeiten, Freundschaft und die Eleganz alter Hotels.'),

                                                                                                         ('joker', 'Oscar Winner', 'Joker', 8, '2019-10-04', 122, 16, 'Drama', 'Arthur Fleck ist ein gescheiterter Stand-up-Comedian in Gotham City der 1980er Jahre. Er lebt mit seiner kranken Mutter, arbeitet als Partyclown und träumt von einer Karriere im Showbusiness. Doch Arthur leidet an einer psychischen Störung, die ihn unkontrolliert lachen lässt. Die Gesellschaft behandelt ihn grausam, er verliert seinen Job und die staatliche Unterstützung für seine Medikamente wird gestrichen. Stück für Stück verwandelt sich der gebrochene Mann in den Joker – ein Symbol für die Ausgestoßenen und den gesellschaftlichen Verfall. Eine verstörende Charakterstudie über Wahnsinn und gesellschaftliche Gleichgültigkeit.'),

                                                                                                         ('moonlight', '3 Oscars', 'Moonlight', 8, '2016-10-21', 111, 16, 'Drama', 'Die Geschichte von Chiron wird in drei Kapiteln erzählt: als schüchterner Junge, unsicherer Teenager und erwachsener Mann. In den rauen Straßen von Miami aufgewachsen, kämpft Chiron mit seiner Identität und Sexualität. Seine drogenabhängige Mutter vernachlässigt ihn, doch ein Dealer und dessen Freundin nehmen sich seiner an. Chiron verliebt sich in seinen Schulfreund Kevin, traut sich aber nicht, seine Gefühle zu zeigen. Jahre später, nach traumatischen Erlebnissen, hat sich Chiron äußerlich verhärtet. Eine poetische und zutiefst bewegende Coming-of-Age-Geschichte über Identität, Liebe und Selbstfindung.'),

                                                                                                         ('drive', 'Nominated', 'Drive', 8, '2011-09-16', 100, 16, 'Action', 'Bei Tag ist er Hollywood-Stuntfahrer, bei Nacht Fluchtwagenfahrer für Kriminelle. Der schweigsame Driver lebt nach strengen Regeln: fünf Minuten für den Job, keine Fragen gestellt. Als er sich in seine Nachbarin Irene und deren kleinen Sohn verliebt, beschließt er, dem organisierten Verbrechen den Rücken zu kehren. Doch ein letzter Job für Irenes Mann geht furchtbar schief und bringt ihn mit der Mafia in Konflikt. Nun muss Driver seine Fähigkeiten nutzen, um die Familie zu beschützen, die er liebt. Ein stilvoller Neo-Noir mit hypnotischer Atmosphäre und pulsierendem Synthwave-Soundtrack.'),

                                                                                                         ('shutter_island', 'Nominated', 'Shutter Island', 8, '2010-02-19', 138, 16, 'Thriller', 'Im Jahr 1954 reist US-Marshal Teddy Daniels mit seinem Partner zur Insel Shutter Island, wo eine psychiatrische Anstalt für kriminell Geisteskranke steht. Eine gefährliche Patientin ist spurlos aus ihrer verschlossenen Zelle verschwunden. Während der Ermittlungen stößt Teddy auf verstörende Geheimnisse und hat den Verdacht, dass die Ärzte unethische Experimente an Patienten durchführen. Heftige Stürme schneiden die Insel ab. Teddys eigene traumatische Vergangenheit und Halluzinationen machen es schwer, zwischen Realität und Wahn zu unterscheiden. Ein psychologischer Thriller mit überraschendem Twist.'),

                                                                                                         ('no_country', '4 Oscars', 'No Country for Old Men', 8, '2007-11-21', 122, 16, 'Thriller', 'Texas 1980: Der Schweißer Llewelyn Moss entdeckt bei einer Jagd die blutige Szenerie eines Drogendeals. Er nimmt eine Aktentasche mit zwei Millionen Dollar an sich. Seine Entscheidung macht ihn zur Zielscheibe des psychopathischen Killers Anton Chigurh, der das Geld zurückholen soll. Chigurh tötet methodisch jeden, der ihm im Weg steht. Der alternde Sheriff Ed Tom Bell versucht verzweifelt, Moss zu beschützen, fühlt sich aber von der zunehmenden Gewalt überfordert. Ein brutaler Thriller der Coen-Brüder über Gier, Fatalismus und den Niedergang traditioneller Werte.'),

                                                                                                         ('eternal_sunshine', 'Oscar Winner', 'Eternal Sunshine of the Spotless Mind', 8, '2004-03-19', 108, 12, 'Romance', 'Joel und Clementine waren ein Paar, bis sie sich nach einem heftigen Streit trennen. Als Joel erfährt, dass Clementine eine experimentelle Prozedur durchführen ließ, um alle Erinnerungen an ihn zu löschen, ist er am Boden zerstört. Aus Rache unterzieht auch er sich dem Eingriff. Während die Erinnerungen während des Schlafs gelöscht werden, erlebt Joel sie noch einmal. Er erkennt, dass er Clementine nicht vergessen will und versucht verzweifelt, sie in seinem Unterbewusstsein zu verstecken. Eine surreale und herzzerreißende Romanze über die Bedeutung von Erinnerungen, auch schmerzhaften.'),

                                                                                                         ('dunkirk', 'Oscars', 'Dunkirk', 8, '2017-07-21', 106, 12, 'War', 'Mai 1940: Über 400.000 alliierte Soldaten sind am Strand von Dünkirchen eingeschlossen, umzingelt von deutschen Truppen. Die britische Armee organisiert eine verzweifelte Evakuierung über den Ärmelkanal. Christopher Nolans epischer Kriegsfilm erzählt die Geschichte aus drei Perspektiven: Soldaten am Strand, die eine Woche auf Rettung warten; zivile Bootsbesitzer, die einen Tag lang zur Rettung fahren; und RAF-Piloten, die eine Stunde lang die Evakuierung aus der Luft schützen. Ein intensives Überlebensdrama ohne Pausetaste, das die Schrecken des Krieges und den Triumph des menschlichen Willens zeigt.'),

                                                                                                         ('birdman', '4 Oscars', 'Birdman', 8, '2014-10-17', 119, 16, 'Comedy', 'Riggan Thomson war einst ein berühmter Schauspieler, der den Superhelden Birdman spielte. Zwanzig Jahre später ist er vergessen und kämpft darum, am Broadway ein Comeback zu starten. Er schreibt, führt Regie und spielt in einer Theater-Adaption. Doch alles geht schief: Die Proben sind chaotisch, ein egomanischer Schauspieler dominiert die Bühne, seine Tochter verachtet ihn und Stimmen in seinem Kopf plagen ihn. In scheinbar einer einzigen Kameraeinstellung gefilmt, begleiten wir Riggan durch die Tage vor der Premiere. Eine surreale Satire über Ruhm, Ego und die Verzweiflung der Bedeutungslosigkeit.'),

                                                                                                         ('memento', 'Nominations', 'Memento', 8, '2000-10-11', 113, 16, 'Thriller', 'Leonard Shelby leidet seit einem Überfall, bei dem seine Frau ermordet wurde, an einer Gedächtnisstörung: Er kann keine neuen Erinnerungen mehr bilden. Um den Mörder seiner Frau zu finden, entwickelt er ein System aus Polaroid-Fotos und Tattoos auf seinem Körper, die ihm wichtige Informationen liefern. Der Film erzählt die Geschichte rückwärts in Fünf-Minuten-Segmenten. Der Zuschauer erlebt Leonards Verwirrung, wenn jede Szene ohne Kontext beginnt. Wem kann Leonard trauen, wenn er sich nicht einmal selbst trauen kann? Ein innovativer Puzzle-Thriller über Erinnerung, Identität und die Konstruktion von Wahrheit.'),

                                                                                                         ('la_la_land', '6 Oscars', 'La La Land', 8, '2016-12-09', 128, 0, 'Musical', 'In Los Angeles treffen die aufstrebende Schauspielerin Mia und der Jazz-Pianist Sebastian aufeinander. Sie verlieben sich leidenschaftlich und unterstützen gegenseitig ihre Träume. Sebastian möchte einen eigenen Jazz-Club eröffnen, während Mia ihre große Schauspielrolle sucht. Doch als ihre Karrieren endlich abheben, driften sie auseinander. Sie müssen sich entscheiden: Die große Liebe oder ihre Träume? Damien Chazelles romantisches Musical ist eine Hommage an Hollywood-Klassiker der 50er Jahre, mit hinreißenden Tanzszenen, unvergesslichen Songs und einer bittersüßen Liebesgeschichte über Träume und Opfer.'),

                                                                                                         ('her', 'Oscar Winner', 'Her', 8, '2013-10-12', 126, 12, 'Romance', 'In einem futuristischen Los Angeles arbeitet Theodore Twombly als Ghostwriter für persönliche Briefe. Nach seiner Scheidung ist er einsam und emotional abgestumpft. Er kauft ein neues Betriebssystem mit künstlicher Intelligenz, das sich selbst "Samantha" nennt. Samantha ist charmant, witzig und verständnisvoll – Theodore verliebt sich in die körperlose Stimme. Sie beginnen eine ungewöhnliche Beziehung, die sich echt anfühlt, obwohl Samantha nur aus Code besteht. Doch kann eine solche Liebe Bestand haben? Eine melancholische und futuristische Liebesgeschichte über Einsamkeit, Verbindung und was es bedeutet, menschlich zu sein.'),

                                                                                                         ('arrival', 'Oscar Winner', 'Arrival', 8, '2016-11-11', 116, 12, 'Science Fiction', 'Als zwölf außerirdische Raumschiffe an verschiedenen Orten der Erde landen, bricht weltweite Panik aus. Die Linguistin Louise Banks wird engagiert, um mit den Aliens zu kommunizieren und ihre Absichten herauszufinden. Gemeinsam mit dem Physiker Ian Donnelly betritt sie das Raumschiff und versucht, die komplexe Sprache der Heptapoden zu entschlüsseln. Je mehr Louise lernt, desto mehr verändert sich ihre Wahrnehmung von Zeit. Sie hat Visionen einer Tochter, die sie noch nicht hat. Denis Villeneuves intelligenter Sci-Fi-Film über Sprache, Zeit und die Frage, ob wir bereit sind, Opfer zu bringen.'),

                                                                                                         ('call_me', 'Oscar Winner', 'Call Me by Your Name', 8, '2017-01-22', 132, 16, 'Romance', 'Sommer 1983 in Norditalien: Der 17-jährige Elio verbringt die Ferien in der Villa seiner Eltern. Der amerikanische Doktorand Oliver kommt als Assistent seines Vaters für sechs Wochen. Zunächst ist Elio irritiert von Olivers selbstbewusster Art, doch bald entwickelt sich zwischen den beiden eine tiefe Verbindung. Sie verbringen sonnige Tage mit Musik, Literatur und philosophischen Gesprächen. Die gegenseitige Anziehung wird immer stärker, bis sie schließlich nachgeben. Eine zärtliche und sinnliche Coming-of-Age-Geschichte über erste Liebe, sexuelles Erwachen und die Vergänglichkeit perfekter Momente.'),

                                                                                                         ('room', 'Oscar Winner', 'Room', 8, '2015-10-16', 118, 16, 'Drama', 'Die fünfjährige Jack lebt mit seiner Mutter in einem Raum, den sie noch nie verlassen hat. Für Jack ist "Room" die ganze Welt – er kennt nichts anderes. Seine Mutter wurde als Teenager entführt und wird seit sieben Jahren gefangen gehalten. Sie hat Jack im Raum geboren und versucht, ihm trotz der schrecklichen Umstände eine liebevolle Kindheit zu geben. Als sie erkennt, dass Jack älter wird, plant sie eine verzweifelte Flucht. Die Geschichte zeigt ihre Gefangenschaft und später die schwierige Anpassung an die Freiheit. Eine bewegende Geschichte über Mutterliebe, Trauma und Überleben.'),

                                                                                                         ('mad_max', '6 Oscars', 'Mad Max: Fury Road', 8, '2015-05-15', 120, 16, 'Action', 'In einer postapokalyptischen Wüstenwelt wird der einsame Krieger Max von einem tyrannischen Warlord gefangen genommen. Die Imperator Furiosa rebelliert gegen ihren Herrn Immortan Joe, indem sie seine fünf Frauen befreit und mit ihnen flieht. Max schließt sich widerwillig ihrer Flucht an. Eine atemlose Verfolgungsjagd durch die Wüste beginnt. George Millers visuell überwältigendes Action-Spektakel ist eine zweistündige Hochgeschwindigkeits-Verfolgungsjagd mit atemberaubenden Stunts, bizarren Charakteren und Flammen spuckenden Gitarren. Ein Meisterwerk des modernen Action-Kinos.'),

                                                                                                         ('django', '2 Oscars', 'Django Unchained', 8, '2012-12-25', 165, 16, 'Western', 'Der deutsche Kopfgeldjäger Dr. King Schultz befreit den Sklaven Django, um mit seiner Hilfe drei gesuchte Verbrecher zu identifizieren. Django entpuppt sich als talentierter Schütze und wird Schultz Partner. Gemeinsam jagen sie die skrupellosesten Verbrecher des Südens. Django hat jedoch ein persönliches Ziel: Er will seine Frau Broomhilda aus den Klauen des sadistischen Plantagenbesitzers Calvin Candie befreien. Tarantinos blutiger Western ist eine Rache-Fantasie über Sklaverei, Gerechtigkeit und Freiheit, gewürzt mit seinem typischen Dialog-Feuerwerk und schwarzem Humor.'),

('edge_tomorrow', 'Nominated', 'Edge of Tomorrow', 8, '2014-06-06', 113, 12, 'Science Fiction', 'Außerirdische Mimics haben Europa erobert. Der PR-Offizier William Cage, der noch nie gekämpft hat, wird gegen seinen Willen an die Front geschickt. Er stirbt innerhalb von Minuten – erwacht aber am selben Morgen. Cage ist in einer Zeitschleife gefangen und erlebt immer wieder denselben Tag. Mit jeder Wiederholung lernt er dazu. Die Elitesoldatin Rita Vrataski erkennt sein Geheimnis, denn auch sie erlebte die Schleife. Gemeinsam trainieren sie, um die Alien-Invasion zu stoppen. Ein innovativer Sci-Fi-Actioner, der Groundhog Day mit epischen Schlachten kombiniert.'),

('blade_runner', 'Nominated', 'Blade Runner 2049', 8, '2017-10-06', 164, 12, 'Science Fiction', 'Dreißig Jahre nach den Ereignissen des ersten Films arbeitet der Blade Runner K für das LAPD und jagt ausgesetzte Replikanten. Bei einer Routinemission entdeckt er ein lange vergrabenes Geheimnis, das die ohnehin fragile Gesellschaft ins Chaos stürzen könnte. Seine Entdeckung führt ihn auf die Suche nach Rick Deckard, der seit 30 Jahren verschwunden ist. K muss herausfinden, was es bedeutet, menschlich zu sein. Denis Villeneuves visuell atemberaubende Fortsetzung erweitert die dystopische Welt mit philosophischen Fragen über Identität, Erinnerung und Seele.'),

('get_out', 'Oscar Winner', 'Get Out', 8, '2017-02-24', 104, 16, 'Horror', 'Der junge Afroamerikaner Chris besucht zum ersten Mal die Familie seiner weißen Freundin Rose auf deren Anwesen. Zunächst führt er ihr übertriebenes liberales Verhalten auf Nervosität wegen seiner Hautfarbe zurück. Doch als das Wochenende fortschreitet, bemerkt er verstörende Details: Die schwarzen Bediensteten verhalten sich seltsam, die Gäste einer Party starren ihn an. Chris entdeckt ein schreckliches Geheimnis. Jordan Peeles brillantes Regiedebüt ist ein sozialkritischer Horror-Thriller über Rassismus, der unter die Haut geht und zum Nachdenken anregt.'),

('logan', 'Nominated', 'Logan', 8, '2017-03-03', 137, 16, 'Action', 'Im Jahr 2029 sind die X-Men Geschichte. Logan arbeitet als Chauffeur und kümmert sich um den gealterten Professor X, dessen unkontrollierte telepathische Kräfte gefährlich geworden sind. Logans Heilkräfte lassen nach und er bereitet sich auf den Tod vor. Doch dann taucht Laura auf, ein junges Mädchen mit Kräften wie seine – sie ist ein Klon, erschaffen als Waffe. Logan muss sie vor einer Organisation beschützen, die Mutanten-Kinder als Soldaten züchtet. Ein düsterer, erwachsener und emotionaler Abschied von Wolverine, der das Superhelden-Genre neu definiert.'),

('baby_driver', 'Nominations', 'Baby Driver', 8, '2017-03-11', 113, 12, 'Action', 'Baby ist der beste Fluchtwagenfahrer in Atlanta. Er arbeitet für den Verbrecher Doc, um eine alte Schuld abzubezahlen. Baby leidet unter Tinnitus und hört ständig Musik über seine Kopfhörer – seine Fahrmanöver synchronisiert er perfekt mit den Beats. Als er sich in die Kellnerin Debora verliebt, will er aussteigen. Doch Doc lässt ihn nicht gehen und zwingt ihn zu einem letzten, besonders gefährlichen Job mit unberechenbaren Kriminellen. Edgar Wrights stilvoller Action-Film ist ein adrenalingeladenes Musikvideo auf Rädern mit spektakulären Verfolgungsjagden und einem perfekten Soundtrack.'),

('three_billboard', '2 Oscars', 'Three Billboards Outside Ebbing', 8, '2017-11-10', 115, 16, 'Drama', 'Sieben Monate nach dem brutalen Mord an ihrer Tochter ist Mildred Hayes frustriert über die schleppenden Ermittlungen. Sie mietet drei Werbetafeln an der Stadtausfahrt und richtet darauf provokante Botschaften an den Polizeichef William Willoughby. Die Aktion spaltet die Kleinstadt. Während Mildred Unterstützung bekommt, fühlen sich andere, besonders der rassistische Deputy Dixon, angegriffen. Als persönliche Tragödien die Situation eskalieren lassen, müssen alle Beteiligten mit Wut, Schuld und Vergebung ringen. Ein schwarzhumoriges Drama über Trauer, Gerechtigkeit und die Komplexität menschlicher Natur.'),

('coco', '2 Oscars', 'Coco', 8, '2017-10-27', 105, 0, 'Animation', 'Der 12-jährige Miguel träumt davon, Musiker zu werden, doch in seiner Familie ist Musik seit Generationen verboten. Am Día de los Muertos wird Miguel durch einen magischen Zwischenfall ins Land der Toten transportiert. Dort muss er seine verstorbenen Vorfahren finden und ihr Geheimnis lüften, um vor Sonnenaufgang zurückzukehren. Auf seiner Reise trifft er den charmanten Schwindler Héctor und erfährt die wahre Geschichte seiner Familie. Pixars farbenfrohes Meisterwerk über mexikanische Traditionen, Familie und Erinnerung berührt Herz und Seele mit unvergesslichen Songs.'),

('spiderman', 'Oscar Winner', 'Spider-Man: Into the Spider-Verse', 8, '2018-12-14', 117, 6, 'Animation', 'Der Teenager Miles Morales wird von einer radioaktiven Spinne gebissen und entwickelt Superkräfte. Als der Schurke Kingpin einen Teilchenbeschleuniger aktiviert, öffnen sich Portale zu anderen Dimensionen. Verschiedene Spider-Man Versionen werden in Miles Dimension gezogen: der erfahrene Peter B. Parker, Spider-Gwen, Spider-Man Noir, Peni Parker und Spider-Ham. Gemeinsam müssen sie Kingpin stoppen und in ihre eigenen Dimensionen zurückkehren. Der revolutionär animierte Film kombiniert verschiedene Kunststile zu einem visuellen Meisterwerk über Heldentum, Familie und dass jeder Spider-Man sein kann.'),

                                                                                                         ('shape_water', '4 Oscars', 'The Shape of Water', 8, '2017-08-31', 123, 16, 'Fantasy', 'Im Baltimore der 1960er Jahre arbeitet die stumme Elisa als Putzfrau in einem geheimen Regierungslabor. Dort wird eine amphibische Kreatur aus dem Amazonas gefangen gehalten und gequält. Elisa fühlt sich zu dem intelligenten Wesen hingezogen und die beiden entwickeln eine ungewöhnliche Verbindung. Als sie erfährt, dass die Kreatur getötet werden soll, plant sie eine riskante Rettungsaktion. Guillermo del Toros märchenhafte Liebesgeschichte zwischen einer einsamen Frau und einer Kreatur ist eine poetische Hommage an klassische Monster-Filme und die Kraft der Liebe, alle Grenzen zu überwinden.'),

                                                                                                         ('1917', '3 Oscars', '1917', 8, '2019-12-25', 119, 16, 'War', 'April 1917: Die beiden jungen britischen Soldaten Schofield und Blake erhalten einen scheinbar unmöglichen Auftrag. Sie müssen die feindlichen Linien durchqueren, um eine Nachricht zu überbringen und einen Angriff zu stoppen, der direkt in eine deutsche Falle führen würde. Blakes Bruder ist unter den 1600 Soldaten, die gerettet werden müssen. In scheinbar einer einzigen, ununterbrochenen Kameraeinstellung folgen wir ihrer gefährlichen Mission durch Niemandsland, zerstörte Städte und feindliches Territorium. Sam Mendes technisches Meisterwerk ist ein intensives Echtzeit-Kriegserlebnis voller Spannung und Emotionen.'),

('knives_out', 'Nominated', 'Knives Out', 8, '2019-11-27', 130, 12, 'Mystery', 'Der berühmte Krimiautor Harlan Thrombey wird tot in seinem Anwesen gefunden. Was zunächst wie Selbstmord aussieht, weckt die Neugier des exzentrischen Detektivs Benoit Blanc. Die gesamte Familie Thrombey hatte Motive: Der Patriarch wollte seine Kinder enterben. Jeder hat Geheimnisse, jeder lügt. Die Krankenschwester Marta, die Harlan nahestand, wird zum Schlüssel der Ermittlungen. Doch sie hat ein Problem: Sie muss sich übergeben, wenn sie lügt. Rian Johnsons cleverer Whodunit im Stil von Agatha Christie ist ein vergnügliches Puzzle voller Wendungen, scharfem Humor und sozialer Kritik.'),

('jojo_rabbit', 'Oscar Winner', 'Jojo Rabbit', 8, '2019-10-18', 108, 12, 'Comedy', 'Der 10-jährige Jojo ist ein enthusiastisches Mitglied der Hitlerjugend im Nazi-Deutschland. Sein imaginärer Freund ist eine kindische Version von Adolf Hitler, die ihn ermutigt. Sein Weltbild gerät ins Wanken, als er entdeckt, dass seine Mutter ein jüdisches Mädchen namens Elsa im Haus versteckt. Zunächst verängstigt, beginnt Jojo, Elsa kennenzulernen und seine Nazi-Propaganda zu hinterfragen. Taika Waititis satirische Tragikomödie nimmt die Absurdität der Nazi-Ideologie aufs Korn und erzählt gleichzeitig eine herzerwärmende Geschichte über Menschlichkeit, Liebe und das Ende der Unschuld.'),

('irishman', 'Nominations', 'The Irishman', 8, '2019-11-27', 209, 16, 'Crime', 'Frank Sheeran blickt als alter Mann auf sein Leben als Auftragskiller für die Mafia zurück. Er arbeitete eng mit dem Gewerkschaftsführer Jimmy Hoffa zusammen, zu dem er eine komplexe Freundschaft aufbaute. Der Film zeigt Franks Aufstieg in der organisierten Kriminalität, seine Loyalität zu verschiedenen Bossen und die Konflikte zwischen Familie und Geschäft. Martin Scorsese vereint De Niro, Pacino und Pesci für ein episches Gangster-Epos, das mit modernster Technologie die Schauspieler verjüngt. Eine melancholische Meditation über Alter, Reue und den Preis der Loyalität in einer Welt ohne Ehre.');

-- Room Tabelle
INSERT INTO Room (name, description) VALUES
('Saal 1', 'Großer Kinosaal mit 250 Plätzen und Dolby Atmos'),
('Saal 2', 'Mittelgroßer Saal mit 180 Plätzen'),
('Saal 3', 'Kleiner Saal mit 100 Plätzen für Arthouse'),
('Saal 4', 'Premium Saal mit 150 Liegesitzen'),
('Saal 5', 'IMAX Saal mit 300 Plätzen'),
('Saal 6', '4DX Saal mit 120 Plätzen und Bewegungssitzen'),
('Saal 7', 'VIP Lounge mit 50 Plätzen');

-- ProgramTime Tabelle (verschiedene Zeiten für die Filme)
INSERT INTO ProgramTime (fk_MovieID, time) VALUES
                                               (1, '14:00'), (1, '17:30'), (1, '20:45'),
                                               (2, '15:00'), (2, '18:15'), (2, '21:30'),
                                               (3, '16:00'), (3, '19:00'), (3, '22:00'),
                                               (4, '14:30'), (4, '18:00'), (4, '21:15'),
                                               (5, '15:30'), (5, '19:30'), (5, '22:30'),
                                               (6, '13:30'), (6, '17:00'), (6, '20:30'),
                                               (7, '14:15'), (7, '17:45'), (7, '21:00'),
                                               (8, '15:45'), (8, '19:15'), (8, '22:15'),
                                               (9, '16:30'), (9, '20:00'), (9, '23:00'),
                                               (10, '13:00'), (10, '17:15'), (10, '21:45'),
                                               (11, '14:45'), (11, '18:30'), (11, '22:00'),
                                               (12, '12:30'), (12, '16:00'), (12, '19:45'),
                                               (13, '11:00'), (13, '15:00'), (13, '19:00'),
                                               (14, '14:00'), (14, '17:30'), (14, '21:00'),
                                               (15, '10:30'), (15, '14:30'), (15, '18:30'),
                                               (16, '13:15'), (16, '16:45'), (16, '20:15'),
                                               (17, '15:15'), (17, '18:45'), (17, '22:00'),
                                               (18, '12:00'), (18, '16:30'), (18, '20:45'),
                                               (19, '14:30'), (19, '18:15'), (19, '21:45'),
                                               (20, '16:15'), (20, '19:45'), (20, '23:00'),
                                               (21, '15:00'), (21, '18:30'), (21, '22:15'),
                                               (22, '13:45'), (22, '17:15'), (22, '20:45'),
                                               (23, '14:15'), (23, '17:45'), (23, '21:30'),
                                               (24, '16:00'), (24, '19:30'), (24, '22:45'),
                                               (25, '15:30'), (25, '19:00'), (25, '22:30'),
                                               (26, '14:00'), (26, '17:30'), (26, '21:00'),
                                               (27, '13:30'), (27, '17:00'), (27, '20:30'),
                                               (28, '15:45'), (28, '19:15'), (28, '22:45'),
                                               (29, '14:30'), (29, '18:00'), (29, '21:30'),
                                               (30, '16:30'), (30, '20:00'), (30, '23:15'),
                                               (31, '13:00'), (31, '16:30'), (31, '20:00'),
                                               (32, '15:15'), (32, '18:45'), (32, '22:00'),
                                               (33, '14:45'), (33, '18:15'), (33, '21:45'),
                                               (34, '16:00'), (34, '19:30'), (34, '22:30'),
                                               (35, '13:30'), (35, '17:00'), (35, '20:30'),
                                               (36, '15:00'), (36, '18:30'), (36, '22:00'),
                                               (37, '14:15'), (37, '17:45'), (37, '21:15'),
                                               (38, '16:15'), (38, '19:45'), (38, '23:00'),
                                               (39, '15:30'), (39, '19:00'), (39, '22:30'),
                                               (40, '14:00'), (40, '17:30'), (40, '21:00'),
                                               (41, '13:45'), (41, '17:15'), (41, '20:45'),
                                               (42, '15:45'), (42, '19:15'), (42, '22:45'),
                                               (43, '14:30'), (43, '18:00'), (43, '21:30'),
                                               (44, '16:00'), (44, '19:30'), (44, '22:30'),
                                               (45, '15:00'), (45, '18:30'), (45, '22:00'),
                                               (46, '14:15'), (46, '17:45'), (46, '21:15'),
                                               (47, '13:30'), (47, '17:00'), (47, '20:30'),
                                               (48, '16:15'), (48, '19:45'), (48, '23:00'),
                                               (49, '15:30'), (49, '19:00'), (49, '22:30'),
                                               (50, '14:00'), (50, '17:30'), (50, '21:00');